# Generated by Django 5.2.1 on 2025-05-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_position_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
